/*
 * @Author: Lambda
 * @Begin: 2020-06-16 19:06:08
 * @Update: 2020-06-17 17:24:44
 * @Update log: 更新日志
 */
export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
};
